# Generated by Django 4.1.2 on 2025-04-20 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Пройдено тестів')),
                ('best_wpm', models.PositiveIntegerField(default=0, verbose_name='Найкращий WPM')),
                ('average_wpm', models.FloatField(default=0, verbose_name='Середній WPM')),
                ('total_chars', models.PositiveIntegerField(default=0, verbose_name='Всього символів')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика користувача',
                'verbose_name_plural': 'Статистики користувачів',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.PositiveIntegerField(verbose_name='Слів за хвилину')),
                ('accuracy', models.FloatField(verbose_name='Точність')),
                ('correct_words', models.PositiveIntegerField(verbose_name='Правильні слова')),
                ('wrong_words', models.PositiveIntegerField(verbose_name='Неправильні слова')),
                ('correct_chars', models.PositiveIntegerField(verbose_name='Правильні символи')),
                ('wrong_chars', models.PositiveIntegerField(verbose_name='Неправильні символи')),
                ('test_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата тесту')),
                ('language', models.CharField(default='en', max_length=2, verbose_name='Мова')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат тесту',
                'verbose_name_plural': 'Результати тестів',
                'ordering': ['-wpm'],
            },
        ),
    ]
